export type AgeGroupData = {
  start_age: number;
  end_age: number;
  name: string;
  themes: string[];
}[];

export const AGE_GROUPS: AgeGroupData = [
  {
    start_age: 0,
    end_age: 2,
    name: 'Infant',
    themes: [
      'Basic Concepts (e.g., Shapes, Colors)',
      'Bath Time',
      'Bedtime',
      'Lullabies',
      'Nature and Seasons',
      'On the Farm',
      'Peekaboo',
      'Sensory Exploration',
    ],
  },
  {
    start_age: 2,
    end_age: 3,
    name: 'Toddler',
    themes: [
      'All About Me',
      'Alphabet and Language',
      'Animals',
      'Bugs',
      'Butterflies',
      'Colors and Shapes',
      'Daily Routines',
      'Fairy Tales and Fantasy',
      'Family and Friends',
      'Music and Movement',
      'Nature and Seasons',
      'Numbers and Counting',
      'Vehicles and Transportation',
    ],
  },
  {
    start_age: 3,
    end_age: 5,
    name: 'Preschool',
    themes: [
      'Acceptance',
      'Adventure',
      'Animals',
      'Art and Creativity',
      'Basic Math Concepts',
      'Bedtime',
      'Big Changes',
      'Community Helpers',
      'Courage',
      'Cultural Traditions Around the World',
      'Dinosaurs and Prehistoric Life',
      'Discovery (Learning)',
      'Empathy',
      'Family',
      'Famous Legends and Myths',
      'Feelings and Emotions',
      'Friendship',
      'Growing Up',
      'Healthy Eating and Foods',
      'Holidays',
      'Imagination',
      'Insects and Bugs',
      'Music and Instruments',
      'Nature',
      'Numbers',
      'Opposites',
      'Physical Activities and Sports',
      'Plants and Gardens',
      'School',
      'Seasons',
      'Shapes',
      'Sharing',
      'Simple Science Experiments',
      'Social Issues',
      'Space Exploration',
      'Suffering',
      'Teamwork',
      'Transportation',
      'Underwater Worlds',
    ],
  },
  {
    start_age: 5,
    end_age: 7,
    name: 'Kindergarten',
    themes: [
      'Ancient Civilizations',
      'Animal Habitats',
      'Arts and Crafts Projects',
      'Basic Coding and Technology',
      'Community',
      'Creativity',
      'Curiosity',
      'Environmental Conservation',
      'Fairy Tales',
      'Folktales from Different Cultures',
      'Geography and World Maps',
      'Historical Figures and Heroes',
      'History',
      'Independence',
      'Introduction to Languages',
      'Magic',
      'Math Puzzles and Games',
      'Mindfulness and Yoga for Kids',
      'Perseverance',
      'Problem Solving',
      'Reading and Writing Fun',
      'Science',
      'Simple Machines and How They Work',
      'Solar System and Planets',
      'Space',
      'Superheroes',
      'Weather and Climate',
      'Wonders of the World',
    ],
  },
  {
    start_age: 7,
    end_age: 9,
    name: 'Early Elementary',
    themes: [
      'Animal Adaptations',
      'Arts and Crafts',
      'Body Systems and Health',
      'Building and Construction',
      'Character Education',
      'Classical Music and Composers',
      'Conservation',
      'Dinosaurs',
      'Diversity',
      'Ecosystems and Biodiversity',
      'Environment',
      'Exploration',
      'Fairy Tales and Myths',
      'Famous Artists and Painters',
      'Friendship',
      'Geometric Shapes and Patterns',
      'Global Festivals and Holidays',
      'Historical Events',
      'Holidays and Celebrations',
      'Identity',
      'Innovation',
      'Invention',
      'Inventions and Inventors',
      'Leadership',
      'Music and Instruments',
      'Oceanography and Marine Life',
      'Overcoming Challenges',
      'Pirates and Adventures',
      'Plant Life Cycles',
      'Robots and Technology',
      'Self-Discovery',
      'Space Missions and Astronauts',
      'Trucks, Trains, and Cars',
      'Teamwork',
      'Water Cycle and Conservation',
    ],
  },
  {
    start_age: 9,
    end_age: 11,
    name: 'Middle Elementary',
    themes: [
      'Art',
      'Business Basics',
      'Coming of Age',
      'Critical Thinking and Problem Solving',
      'Cultural Diversity',
      'Earth Sciences and Geology',
      'Empowerment',
      'Future',
      'Global Awareness',
      'Human Rights',
      'Identity',
      'Making a Difference',
      'Resilience',
      'Science',
      'Social Justice',
      'Technology',
      'World Geography and Landmarks',
    ],
  },
  {
    start_age: 11,
    end_age: 13,
    name: 'Late Elementary',
    themes: [
      'Adolescence',
      'Adventure and Mystery',
      'Animal Stories',
      'Comic Books and Graphic Novels',
      'Decision Making',
      'DIY Projects and Crafts',
      'Ethics',
      'Fantasy and Magic',
      'Growing Pains',
      'Historical Fiction',
      'Identity',
      'Independence',
      'Jokes and Riddles',
      'Morality',
      'Peer Relationships',
      'Personal Growth',
      'Science Fiction',
      'Self-Expression',
      'Snow and mountains',
      'Sports and Athletics',
      'Superheroes and Villains',
      'Transition',
    ],
  },
];

export type StoryLengthRange = {
  min: number;
  max: number;
};

export const STORY_LENGTH_RANGE: StoryLengthRange = {
  min: 100,
  max: 5000,
};

export const STORY_LENGTH_MIDPOINT = Math.floor(
  (STORY_LENGTH_RANGE.max + STORY_LENGTH_RANGE.min) / 2
);
